replicaCount: 2

image:
  repository: rick-morty-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: dev.rick-morty.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
