apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rick-morty-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rick-morty-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "rick-morty-app.name" . }}
    spec:
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.service.port }}
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.service.port }}
