name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python for CSV dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Build Docker image
        run: docker build -t rick-morty-api-service:ci .

      - name: Run container
        run: |
          docker run -d --name rick-morty-api -p 8000:8000 rick-morty-api-service:ci
          # נחכה עד שהשרתי יהיה זמין
          for i in {1..15}; do
            curl -sf http://localhost:8000/healthcheck && break
            echo "Waiting for API to start..."
            sleep 2
          done

      - name: Test /healthcheck
        run: |
          curl -sf http://localhost:8000/healthcheck

      - name: Test /characters endpoint
        run: |
          curl -sf http://localhost:8000/characters | head -n1

      - name: Test /characters/csv endpoint
        run: |
          curl -sf http://localhost:8000/characters/csv | head -n1

      - name: Cleanup container
        if: always()
        run: docker rm -f rick-morty-api