# .github/workflows/ci-cd.yaml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-load-image:
    name: Build Docker image & load into KinD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies for scripts
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install requests flask

      - name: Build Docker image
        run: docker build -t rick-morty-app:ci -f api-service/Dockerfile .

      - name: Set up KinD cluster
        uses: engineerd/setup-kind@v0.6.0
        with:
          version: "v0.24.0"

  deploy-to-kind:
    name: Deploy to Kubernetes & test
    needs: build-and-load-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl & Helm
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy Helm chart
        run: |
          helm upgrade --install ci-app helm-chart \
            --namespace ci --create-namespace \
            --set image.repository=rick-morty-app \
            --set image.tag=ci \
            --set ingress.enabled=false

      - name: Wait for rollout
        run: kubectl rollout status deployment/rick-morty-app -n ci

      - name: Run smoke tests
        run: |
          POD=$(kubectl get pods -n ci -l app=rick-morty-app -o jsonpath="{.items[0].metadata.name}")
          kubectl port-forward -n ci $POD 8080:80 &
          sleep 10
          curl -f http://127.0.0.1:8080/healthcheck
          curl -f http://127.0.0.1:8080/characters
